version: "3"

interval: 500ms

vars:
  PROJECT: "Saturn-API"
  REDBEAN: "{{.PROJECT}}.com"
  REDBEAN_VERSION: "3.0.0"

tasks:
  default:
    desc: "Run all tasks"
    cmds:
      - task: download 
      - task: add 
      - task: start
  download:
    vars: 
      UTILS: [ 
        "https://redbean.dev/redbean-3.0.0.com",
        "https://redbean.dev/sqlite3.com",
        "https://redbean.dev/zip.com",
        "https://redbean.dev/unzip.com",
        "https://raw.githubusercontent.com/jart/cosmopolitan/2.2/tool/net/definitions.lua"
      ]
    sources:
      - utils/redbean-3.0.0.com
      - utils/sqlite3.com
      - utils/zip.com
      - utils/unzip.com
      - utils/definitions.lua
    cmds:
      - mkdir -p src && mkdir -p utils
      - for: 
          var: UTILS
        cmd: cd utils && curl {{.ITEM}} -o $(basename {{.ITEM}}) && chmod +x $(basename {{.ITEM}})
  add: 
    cmds:
      # - cp -f utils/redbean-{{.REDBEAN_VERSION}}.com {{.REDBEAN}}
      - cd src && zip -r ../utils/redbean-{{.REDBEAN_VERSION}}.com . --out ../{{.REDBEAN}}
      # maybe use the zip 'filesync feature?'
  start: 
    cmds:
      - chmod +x {{.REDBEAN}}
      - sh ./{{.REDBEAN}} -vv
  clean: 
    cmds:
      - rm -r utils/ --force
      - rm -r {{.REDBEAN}}  --force
      - rm -r {{.PROJECT}}.log  --force
      - rm -r .task/checksum --force
  dev: 
    desc: Builds and watches on any changes 
    watch: true
    sources:
      - 'src/*'
      - 'src/*/*' 
    cmds: 
      - task: add
      - task: start
